spring.application.name=hedi

spring.datasource.url=jdbc:postgresql://hedi_mainstream_user:qNEMFha7oHilFeoczn89FEtWN8FCJ7dc@dpg-d8641n37uimc73butkmg-a/hedi_mainstream
spring.datasource.username=hedi_mainstream_user
spring.datasource.password=qNEMFha7oHilFeoczn89FEtWN8FCJ7dc
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
server.port=${PORT:8080}
server.servlet.context-path=/


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.deepLinking=true
springdoc.swagger-ui.displayOperationId=true

jwt.secret=Seccretttookkeennffffoooorrrrjjjjwwttttoookkeennnnn1234567890
jwt.expiration=86400000
jwt.refresh.expiration=604800000

google.oauth.client-id=1072043026462-47uq1p82pada82f6a0f6jt9sfpntj1qi.apps.googleusercontent.com
google.oauth.client-secret=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
google.oauth.redirect-uri=postmessage

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nhatminhdt23@gmail.com
spring.mail.password=byot dcsy rpnk zvju
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000